ARG SAASHQ_BRANCH=main

FROM saashq/build:${SAASHQ_BRANCH} AS builder

ARG SAASHQ_BRANCH=main
ARG SAASHQ_PATH=https://github.com/saashqdev/saashq
ARG APPS_JSON_BASE64

USER root

RUN if [ -n "${APPS_JSON_BASE64}" ]; then \
    mkdir /opt/saashq && echo "${APPS_JSON_BASE64}" | base64 -d > /opt/saashq/apps.json; \
  fi

USER saashq

RUN export APP_INSTALL_ARGS="" && \
  if [ -n "${APPS_JSON_BASE64}" ]; then \
    export APP_INSTALL_ARGS="--apps_path=/opt/saashq/apps.json"; \
  fi && \
  wrench init ${APP_INSTALL_ARGS}\
    --saashq-branch=${SAASHQ_BRANCH} \
    --saashq-path=${SAASHQ_PATH} \
    --no-procfile \
    --no-backups \
    --skip-redis-config-generation \
    --verbose \
    /home/saashq/saashq-wrench && \
  cd /home/saashq/saashq-wrench && \
  echo "{}" > sites/common_site_config.json && \
  find apps -mindepth 1 -path "*/.git" | xargs rm -fr

FROM saashq/base:${SAASHQ_BRANCH} AS backend

USER saashq

COPY --from=builder --chown=saashq:saashq /home/saashq/saashq-wrench /home/saashq/saashq-wrench

WORKDIR /home/saashq/saashq-wrench

VOLUME [ \
  "/home/saashq/saashq-wrench/sites", \
  "/home/saashq/saashq-wrench/sites/assets", \
  "/home/saashq/saashq-wrench/logs" \
]

CMD [ \
  "/home/saashq/saashq-wrench/env/bin/gunicorn", \
  "--chdir=/home/saashq/saashq-wrench/sites", \
  "--bind=0.0.0.0:8000", \
  "--threads=4", \
  "--workers=2", \
  "--worker-class=gthread", \
  "--worker-tmp-dir=/dev/shm", \
  "--timeout=120", \
  "--preload", \
  "saashq.app:application" \
]
